### ISSUE TITLE
add ingress for volume servers

### ISSUE THREAD

**Issue by chrislusf** [seaweedfs/seaweedfs-operator#16]

**Comment by chrislusf** [comment]
Each volume server needs one service, in order to be accessed from outside of k8s.

Current volume servers are behind "seaweed1-volume-peer" and "seaweed1-volume" services. But there seem no use of the services.

**Comment by howardlau1999** [comment]
The peer svc is not for end user purpose but for statefulset. The other one may need refactoring to generate one for each volume server.
________________________________

**Comment by chrislusf** [comment]
Added a commit to add a service for each volume server
