### ISSUE TITLE
Integrate a weed master client to communicate with masters

### ISSUE THREAD

**Issue by howardlau1999** [seaweedfs/seaweedfs-operator#23]

**Comment by chrislusf** [comment]
This is not useful since masters are not accessible from the operator.

**Comment by howardlau1999** [comment]
We need this to execute the evacuate commands. Maybe what I meant to say is a weed shell. From the operator we need to add namespace to the service address otherwise it cannot be resolved.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chrislusf** [comment]
I see. The previous develop steps to run the operator outside of the k8s do not work any more.

Added 771312ddfb3d1d969625042921d5e4d50c707814
