### ISSUE TITLE
Controlled rolling upgrade or restart

### ISSUE THREAD

**Issue by howardlau1999** [seaweedfs/seaweedfs-operator#25]

**Comment by chrislusf** [comment]
Just change the image should work.

**Comment by chrislusf** [comment]
Is this same as https://github.com/seaweedfs/seaweedfs-operator/issues/21 ?

**Comment by howardlau1999** [comment]
Not the same. #21 is focuses on the initial deploy process

**Comment by chrislusf** [comment]
Fixed #21 

Seems the same way to address this issue. Just need to include the image version comparison?

**Comment by howardlau1999** [comment]
Yes. BTW, we don't need all masters are running. Just make sure the minimum count is satisfied. For example, 2 of 3 masters are running.
