### ISSUE TITLE
Something wrong when seaweedfs-operator installed

### ISSUE THREAD

**Issue by hanzhc** [seaweedfs/seaweedfs-operator#30]
I follow the installation information on kubernetes 1.18.6 and the steps are below:
1. git clone https://github.com/seaweedfs/seaweedfs-operator --depth=1
2. install the cert-manager1.2
3. change the value of ENABLE_WEBHOOKS to "true" in config/manager/manager.yaml
4. make deploy
Then I encounter some problem and I need  help:
![Xnip2021-03-01_16-02-55](https://user-images.githubusercontent.com/38808097/109469839-8c7d0f80-7aa9-11eb-8818-aacec9b9204b.jpg)
![Xnip2021-03-01_15-58-22](https://user-images.githubusercontent.com/38808097/109469890-9e5eb280-7aa9-11eb-9fe3-fcc6d77c81b9.jpg)

How can I solve it?

**Comment by chrislusf** [comment]
seems related to the cert manager you installed.
