### ISSUE TITLE
How to get more configuration details about master,filer and volume

### ISSUE THREAD

**Issue by hanzhc** [seaweedfs/seaweedfs-operator#31]
I saw the example in `config/samples/seaweed_v1_seaweed.yaml`. How can I get more  field configuration details about the apiversion `seaweed.seaweedfs.com/v1`?

**Comment by chrislusf** [comment]
See https://github.com/seaweedfs/seaweedfs-operator/blob/master/api/v1/seaweed_types.go#L43
