### ISSUE TITLE
Something wrong happened when the seaweed filer replicas were scaled

### ISSUE THREAD

**Issue by hanzhc** [seaweedfs/seaweedfs-operator#32]
I runed the example in `config/samples/seaweed_v1_seaweed.yaml `.Then I uploaded the file by the filer website page. The result is below:
![image](https://user-images.githubusercontent.com/38808097/110567661-d42c2700-818c-11eb-81ca-53d1bd578963.png)
But when I changed the filer replicas,whatever increase or decrease, and I found nothing in the filer website page.It seams that the filers inited. The result  is below:
![Xnip2021-03-10_10-26-21](https://user-images.githubusercontent.com/38808097/110567494-94fdd600-818c-11eb-975a-ccd52f7776d0.jpg)
Actually,I do not want it happened.
How can I maintain the previous filter data whatever the replicas  are changed? 
Is there some special configuration about filer to solve the problem? Can anyone give me an example?

**Comment by chrislusf** [comment]
You would need a permanent data store, not an embedded one which can go away if the filer is restated. This is not supported yet.
