### ISSUE TITLE
seaweedfs-operator-controller-manager in CrashLoopBackOff for the manager container

### ISSUE THREAD

**Issue by arthurlogilab** [seaweedfs/seaweedfs-operator#46]
Trying to deploy the seaweedfs-operator on one of our kubernetes cluster I get to a point where I can access the http dashboard of seaweed and see the nodes connected together. But I get a seaweedfs-operator-controller-manager in CrashLoopBackOff for the manager container

```
terminated
Reason: OOMKilled - exit code: 137
Started at: 2021-07-15T13:10:32Z
Finished at: 2021-07-15T13:10:57Z
```

Nothing out of the ordinary in the logs : 

```
seaweedfs-operator-controller-manager-54cc768f4c-2t8gp manager 2021-07-15T12:57:08.898Z	INFO	controllers.Seaweed	some masters are not ready	{"sw-master-statefulset": "seaweed1", "missing": 5}
seaweedfs-operator-controller-manager-54cc768f4c-2t8gp manager E0715 12:57:09.302782       1 reflector.go:382] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to watch *v1.Pod: unknown (get pods)
seaweedfs-operator-controller-manager-54cc768f4c-2t8gp manager 2021-07-15T12:57:11.898Z	INFO	controllers.Seaweed	start Reconcile ...	{"seaweed": "default/seaweed1"}
seaweedfs-operator-controller-manager-54cc768f4c-2t8gp manager 2021-07-15T12:57:11.898Z	INFO	controllers.Seaweed	Get master seaweed1	{"seaweed": "default/seaweed1"}
seaweedfs-operator-controller-manager-54cc768f4c-2t8gp manager E0715 12:57:11.899498       1 reflector.go:382] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to watch *v1.Pod: unknown (get pods)
seaweedfs-operator-controller-manager-54cc768f4c-2t8gp manager 2021-07-15T12:57:12.096Z	INFO	controllers.Seaweed	Get master peer service seaweed1-master-peer	{"sw-master-peer-service": "seaweed1"}
seaweedfs-operator-controller-manager-54cc768f4c-2t8gp manager 2021-07-15T12:57:12.115Z	INFO	controllers.Seaweed	Get master service seaweed1-master	{"sw-master-service": "seaweed1"}

```

**Comment by chrislusf** [comment]
seems the docker memory is not enough.

**Comment by arthurlogilab** [comment]
Could this be related to https://github.com/seaweedfs/seaweedfs-operator/blob/master/config/manager/manager.yaml#L38  ? Trying out with with 300Mi (and 200Mi for request) on my deployment.

**Comment by chrislusf** [comment]
updates?

**Comment by arthurlogilab** [comment]
With the bumped limit and request it works better. Judging from what I seen in Lens they are a bit too high, but I haven't pushed the experimentation further than creating one SeaWeed object :  

![Screenshot from 2021-07-20 09-52-55](https://user-images.githubusercontent.com/445200/126283242-51f03913-9901-4a7c-b9ab-0b34ad913ae4.png)

According to this graph I could probably set it to `request` to 50Mi and Limit to 100Mi.

**Comment by chrislusf** [comment]
thanks! Welcome to send a PR!
